-- ============================================================================
-- Agent action audits  (Agent Office Phase 2 — the write-action audit trail)
-- Purpose: append-only log of every action an agent proposes/executes against
--   Katana data. One row per lifecycle event (proposed / approved / rejected /
--   executed / failed), correlated by request_id, with before/after row
--   snapshots for executed mutations. Powers the future Actions tab on
--   /agents/quality and the enterprise audit export.
-- Writers: ONLY the security-definer helper agent_action_audit_log() (called
--   by the ai_act_* action functions and, later, by the engine with the
--   signed-in user's JWT). No direct table write path from clients.
-- Run in the Supabase SQL editor or via MCP apply_migration. Idempotent.
-- Order: apply BEFORE supabase-ai-act-pm-actions-migration.sql.
-- ============================================================================

create extension if not exists "uuid-ossp";

create table if not exists public.agent_action_audits (
  id uuid primary key default uuid_generate_v4(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  -- the signed-in human the agent acted as (writes execute under their JWT)
  user_id uuid references auth.users(id) on delete set null,
  agent_id text,
  agent_name text,
  session_id text,
  -- correlation id for one proposed action's lifecycle (proposed -> executed …);
  -- generated by the engine tool, one per proposal
  request_id text,
  -- namespaced action key, e.g. 'pm.create_task'
  action text not null,
  -- the action arguments as requested (never secrets; plain business fields)
  payload jsonb not null default '{}'::jsonb,
  -- row snapshots for executed mutations (null for create-before / propose-only)
  before_state jsonb,
  after_state jsonb,
  -- engine approval id once the human-approval loop is wired (Phase 2.1)
  approval_id text,
  -- autonomy level the action ran under: 0 propose-only, 1 approve-each, 2 auto
  autonomy_level smallint not null default 0 check (autonomy_level in (0, 1, 2)),
  status text not null default 'proposed'
    check (status in ('proposed', 'approved', 'rejected', 'executed', 'failed')),
  error text,
  created_at timestamptz not null default now()
);

create index if not exists agent_action_audits_org_idx
  on public.agent_action_audits (organization_id, created_at desc);
create index if not exists agent_action_audits_action_idx
  on public.agent_action_audits (organization_id, action, created_at desc);
create index if not exists agent_action_audits_request_idx
  on public.agent_action_audits (organization_id, request_id);

alter table public.agent_action_audits enable row level security;

-- Read is restricted to org owners/admins (same posture as agent_answer_audits):
-- the trail records what agents did on behalf of every user in the org.
drop policy if exists "org_admin_read_agent_action_audits" on public.agent_action_audits;
create policy "org_admin_read_agent_action_audits" on public.agent_action_audits
  for select
  using (
    organization_id = public.get_user_organization_id()
    and exists (
      select 1 from public.user_profiles p
      where p.id = auth.uid() and p.role in ('owner', 'admin')
    )
  );

-- No insert/update/delete policies on purpose: the table is append-only and
-- reachable only through the definer helper below (or the service role).

-- ----------------------------------------------------------------------------
-- agent_action_audit_log() — the ONLY write path into agent_action_audits.
-- SECURITY DEFINER so the (RLS-blocked) insert succeeds, but it:
--   * requires a signed-in user (auth.uid() must resolve),
--   * stamps organization_id from the caller's profile — never from arguments,
--   * only INSERTs (append-only; no update/delete surface exists at all).
-- ----------------------------------------------------------------------------
create or replace function public.agent_action_audit_log(
  p_action text,
  p_status text,
  p_payload jsonb default '{}'::jsonb,
  p_before jsonb default null,
  p_after jsonb default null,
  p_agent_id text default null,
  p_agent_name text default null,
  p_session_id text default null,
  p_request_id text default null,
  p_approval_id text default null,
  p_autonomy_level smallint default 0,
  p_error text default null
) returns uuid
language plpgsql
security definer
set search_path to 'public'
as $$
declare
  v_org uuid;
  v_id uuid;
begin
  if auth.uid() is null then
    raise exception 'not_signed_in';
  end if;
  v_org := public.get_user_organization_id();
  if v_org is null then
    raise exception 'no_organization';
  end if;
  if p_action is null or btrim(p_action) = '' then
    raise exception 'action_required';
  end if;
  if p_status not in ('proposed', 'approved', 'rejected', 'executed', 'failed') then
    raise exception 'invalid_status';
  end if;

  insert into public.agent_action_audits (
    organization_id, user_id, agent_id, agent_name, session_id, request_id,
    action, payload, before_state, after_state, approval_id, autonomy_level,
    status, error
  ) values (
    v_org, auth.uid(), p_agent_id, p_agent_name, p_session_id, p_request_id,
    btrim(p_action), coalesce(p_payload, '{}'::jsonb), p_before, p_after,
    p_approval_id, coalesce(p_autonomy_level, 0), p_status, p_error
  ) returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.agent_action_audit_log(
  text, text, jsonb, jsonb, jsonb, text, text, text, text, text, smallint, text
) from public, anon;
grant execute on function public.agent_action_audit_log(
  text, text, jsonb, jsonb, jsonb, text, text, text, text, text, smallint, text
) to authenticated, service_role;

comment on table public.agent_action_audits is
  'Agent Office action trail: append-only lifecycle log (proposed/approved/rejected/executed/failed) of agent write-actions, with before/after snapshots. Written only via agent_action_audit_log(); read by org owners/admins.';
comment on function public.agent_action_audit_log is
  'Sole write path into agent_action_audits. SECURITY DEFINER, org-stamped from the caller''s JWT, append-only.';
